In [50]:
%pip install --upgrade nltk pandas numpy scikit-learn

Requirement already satisfied: nltk in c:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\site-packages (3.9.3)
Requirement already satisfied: pandas in c:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\site-packages (3.0.1)
Requirement already satisfied: numpy in c:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\site-packages (2.4.3)
Requirement already satisfied: scikit-learn in c:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\site-packages (1.8.0)
Requirement already satisfied: click in c:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in c:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in c:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\site-packages (from nltk) (2026.2.28)
Requirement already satisfied: tqdm in c:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\site-packages (from nltk) (4.67.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\ASUS\AppData\Roaming\Python\Python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: scipy>=1.10.0 in c:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\Users\ASUS\AppData\Local\Programs\Python\Python311\Lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in C:\Users\ASUS\AppData\Roaming\Python\Python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: colorama in C:\Users\ASUS\AppData\Roaming\Python\Python311\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [51]:
#importing necessary libraries
import pandas as pd
import numpy as np
import nltk
import re
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from nltk.stem import wordnet
from sklearn.feature_extraction.text import CountVectorizer
from nltk import pos_tag
from sklearn.metrics import pairwise_distances
from nltk import word_tokenize

#downloading necessary nltk resources
nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger_eng is already up-to-
[nltk_data]       date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [52]:
df=pd.read_csv("C:\\Users\\ASUS\\OneDrive\\Documents\\GITHUB\\SchemeSathi\\Dataset\\SchemeSathi-main-data.csv")

In [53]:
df.head()

,scheme_name,slug,details,benefits,eligibility,application,documents,level,schemeCategory,tags
0,"""Immediate Relief Assistance"" under ""Welfare a...",ira-wrflsncs,"The scheme ""Immediate Relief Assistance"" is a ...","₹ 1,00,000, in two installments of ₹ 50,000 ea...",The applicant should be the family (legal heir...,Step 1: The interested applicant should visit ...,Photograph of the Family (Legal Heir) of the M...,State,"Agriculture,Rural & Environment, Social welfar...","Missing, Fisherman, Relief, Financial Assistan..."
1,AICTE SHORT TERM TRAINING PROGRAMME-SFURTI SCHEME,astpss,"Short Term Training Programme-SFURTI Program, ...","Financial Assistance : Limit of funding ₹ 4,00...",The institution should be AICTE approved.,Registration of New Institute: Step 01: Visit ...,Feedback Form Copy of Proceedings Completion R...,Central,Education & Learning,"Trainings, Financial Assistance, AICTE"
2,Burial and Ex-gratia Payment Scheme in Case of...,baepsicodouldwact,"Launched in 2014, the "" Burial and Ex-gratia P...","Funeral Assistance: ₹3,000 payable in case of ...",The deceased construction worker should have b...,Step 1: The interested applicant should visit ...,Aadhaar Card of the applicant (nominee/Legal h...,State,Social welfare & Empowerment,"Building Worker, Construction Workers, Unregis..."
3,Consortia & Tender Marketing Scheme,ctms,Promotion of the product of Micro and Small En...,Enlistment of the Unit for participating in Go...,Micro & Small Enterprises registered with NSIC...,"Step 01: The application form, in the prescrib...",A passport size photograph of each of the Prop...,Central,Business & Entrepreneurship,"Goods And Services Marketing, Turnkey Projects..."
4,Garuda Scheme for Funeral Expense,gsfe,Andhra Pradesh Brahmin Welfare Corporation (AB...,"Financial Assistance of ₹10,000/- for funeral ...",The applicant should be a close relative of th...,Registration and apply Step 01: Applicants hav...,Passport-size Photograph of the Applicant Aadh...,State,Social welfare & Empowerment,"Social Welfare, Financial Assistance, Deceased..."

In [54]:
df.head(20)

,scheme_name,slug,details,benefits,eligibility,application,documents,level,schemeCategory,tags
0,"""Immediate Relief Assistance"" under ""Welfare a...",ira-wrflsncs,"The scheme ""Immediate Relief Assistance"" is a ...","₹ 1,00,000, in two installments of ₹ 50,000 ea...",The applicant should be the family (legal heir...,Step 1: The interested applicant should visit ...,Photograph of the Family (Legal Heir) of the M...,State,"Agriculture,Rural & Environment, Social welfar...","Missing, Fisherman, Relief, Financial Assistan..."
1,AICTE SHORT TERM TRAINING PROGRAMME-SFURTI SCHEME,astpss,"Short Term Training Programme-SFURTI Program, ...","Financial Assistance : Limit of funding ₹ 4,00...",The institution should be AICTE approved.,Registration of New Institute: Step 01: Visit ...,Feedback Form Copy of Proceedings Completion R...,Central,Education & Learning,"Trainings, Financial Assistance, AICTE"
2,Burial and Ex-gratia Payment Scheme in Case of...,baepsicodouldwact,"Launched in 2014, the "" Burial and Ex-gratia P...","Funeral Assistance: ₹3,000 payable in case of ...",The deceased construction worker should have b...,Step 1: The interested applicant should visit ...,Aadhaar Card of the applicant (nominee/Legal h...,State,Social welfare & Empowerment,"Building Worker, Construction Workers, Unregis..."
3,Consortia & Tender Marketing Scheme,ctms,Promotion of the product of Micro and Small En...,Enlistment of the Unit for participating in Go...,Micro & Small Enterprises registered with NSIC...,"Step 01: The application form, in the prescrib...",A passport size photograph of each of the Prop...,Central,Business & Entrepreneurship,"Goods And Services Marketing, Turnkey Projects..."
4,Garuda Scheme for Funeral Expense,gsfe,Andhra Pradesh Brahmin Welfare Corporation (AB...,"Financial Assistance of ₹10,000/- for funeral ...",The applicant should be a close relative of th...,Registration and apply Step 01: Applicants hav...,Passport-size Photograph of the Applicant Aadh...,State,Social welfare & Empowerment,"Social Welfare, Financial Assistance, Deceased..."
5,Incentive For The Intra Caste Marriage within ...,ifticmwstc,"The scheme ""Incentive for Intra Caste Marriage...","An incentive of ₹2,00,000/- is provided to the...",The couple should be residing in Karnataka. Bo...,Step 1: Visit the official website of the Trib...,Aadhaar Card Bank Account Details Marriage Pro...,State,Social welfare & Empowerment,"Intra Caste, Marriage, Schedule Tribe, Incenti..."
6,Incentive Scheme for MSMEs in Powerloom Sector...,ismpsscis,The scheme “State Capital Investment Subsidy” ...,20% of Fixed Capital Investment on Plant and m...,The Scheme shall be generally applicable to al...,"A micro, small or medium enterprise in Powerlo...",A copy of the Memorandum of Association and Ar...,State,Business & Entrepreneurship,"Powerloom, Incentives, State Capital Investmen..."
7,Indira Mahila Shakti Udyam Protsahan Yojana,imspesy,The Indira Mahila Shakti Udyam Protsahan Yojan...,"Loan Limit Loan amount of ₹ 50,00,000/- to ind...",The applicant's age should be 18 years or more...,Registration Step-1: Applicant have to visit t...,Aadhar card. Address proof. Bank account state...,State,Women and Child,"Women, Empowerment, Development, Motivaction"
8,Mukhyamantri Shramik Aujaar Sahayata Yojana,msasy,The Labor Department of Chhattisgarh launched ...,Tool kits can given free of cost to the regist...,The Applicant must be a native of Chhattisgarh...,Registration of a Construction Worker Under C...,Bank passbook photocopy. Self-declaration cert...,State,Social welfare & Empowerment,"Financial Assistance, Construction Workers, La..."
9,Nirman Shramik Jeevan va Bhavishya Suraksha Yo...,nsjbsy,"Launched in 2016, the scheme ""Nirman Shramik J...",Pradhan Mantri Suraksha Bima Yojana (PMSBY) 10...,1. The applicant must be registered as a bene...,REGISTRATION Step 1: Visit the Official Portal...,Copy of Beneficiary Registration Identity Card...,State,Health & Wellness,"Medical, Insurance, Health, Labor, Premium, Co..."
10,Pre-Matric Scholarship for Backward Class Stud...,pmsfbcs,"The scheme ""Pre-Matric Scholarship for Backwar...",Classes 6th to 8th Boys: ₹20/- per month Girls...,The applicant should be a student of classes 6...,Step 1: The interested applicant should visit ...,Caste Certificate Income Certificate Land Owne...,State,Education & Learning,"Financial Assistance, Backward Class, Student,..."
11,Safai Karmakaar Ke Putr/Putri Hetu Vishesh Coa...,skhvc,Labor Department of Chhattisgarh State started...,The fee for special coaching for admission in ...,Children of registered sanitation workers will...,Unregistered Applicant : All the applicant hav...,Aadhar card. Labor registration Card. Scholars...,State,Education & Learning,"Education, Coaching"
12,The West Bengal Incentive Scheme: Additional I...,wbisaito,“Additional Incentive for Adventure Tour Opera...,Group A: 60% Group B: 70% Group C: 80% Group ...,The Scheme shall be generally applicable to al...,Registration Process: Step 01: Visit the offic...,Documents required for the Registration and El...,State,Business & Entrepreneurship,"Tourism, Incentives, Tour Operators, Tourism U..."
13,The West Bengal Incentive Scheme: Additional I...,wbisaige,“Additional Incentive on Generation of Employm...,"Group A, B, C & D areas: 60% for a period of 5...",The Scheme shall be generally applicable to al...,Registration Process: Step 1: Visit the offici...,Documents required for the Registration and El...,State,Business & Entrepreneurship,"Tourism, Incentives, Waiver, Tourism Units, En..."
14,The West Bengal Incentive Scheme: Capacity Uti...,wbiscu,The scheme “State Capital Investment Subsidy” ...,"Pattern of Assistance: 50%, subject to a maxim...",The Scheme shall be generally applicable to al...,Registration Process: Step 1: Visit the offici...,Documents required for the Registration and El...,State,Business & Entrepreneurship,"Tourism, Entrepreneurship, Capacity Utilisatio..."
15,The West Bengal Incentive Scheme: Interest Sub...,wbisistl,“Interest Subsidy on Term Loan” is a sub schem...,"Group-'A’ and ‘B' areas: 50%, subject to a lim...",The Scheme shall be generally applicable to al...,Registration Process: Step 1: Visit the offici...,Documents required for the Registration and El...,State,Business & Entrepreneurship,"Tourism, Incentives, Interest Subsidy, Tourism..."
16,The West Bengal Incentive Scheme: Reimbursemen...,wbisrsdrf,“Reimbursement of Stamp Duty and Registration ...,"Group A and B: 50%, Group C and D: 60%, Specia...",The Scheme shall be generally applicable to al...,Registration Process: Step 1: Visit the offici...,Documents required for the Registration and El...,State,Business & Entrepreneurship,"Tourism, Incentives, Stamp Duty, Tourism Units..."
17,The West Bengal Incentive Scheme: State Capita...,wbisscis,The scheme “State Capital Investment Subsidy” ...,"Group A: 7.5%, subject to a limit of ₹ 1,00,00...",The Scheme shall be generally applicable to al...,Registration Process: Step 1: Visit the offici...,Documents required for the Registration and El...,State,Business & Entrepreneurship,"Tourism, Incentives, State Capital Investment ..."
18,The West Bengal Incentive Scheme: Subsidy for ...,wbissqi,“Subsidy for Quality Improvement” is a sub sch...,"50%, subject to a maximum of ₹ 7,50,000/-.",The Scheme shall be generally applicable to al...,Registration Process: Step 1: Visit the offici...,Documents required for the Registration and El...,State,Business & Entrepreneurship,"Tourism, Incentives, Quality Improvement, Tour..."
19,The West Bengal Incentive Scheme: Tourism Prom...,wbistpais,The scheme “State Capital Investment Subsidy” ...,Pattern of Assistance: Assistance at the rate ...,The Scheme shall be generally applicable to al...,Registration Process: Step 1: Visit the offici...,Documents required for the Registration and El...,State,Business & Entrepreneurship,"Tourism, Tourism Promotion, Interest Subsidy, ..."

In [55]:
df.shape[0]

3400

In [56]:
df.shape[1]

10

In [57]:
df.isnull().sum()

scheme_name        0
slug               0
details            0
benefits           0
eligibility        0
application        2
documents         11
level              0
schemeCategory     0
tags              29
dtype: int64

Handling Missing Values

In [58]:
df.ffill(axis=0,inplace=True)

,scheme_name,slug,details,benefits,eligibility,application,documents,level,schemeCategory,tags
0,"""Immediate Relief Assistance"" under ""Welfare a...",ira-wrflsncs,"The scheme ""Immediate Relief Assistance"" is a ...","₹ 1,00,000, in two installments of ₹ 50,000 ea...",The applicant should be the family (legal heir...,Step 1: The interested applicant should visit ...,Photograph of the Family (Legal Heir) of the M...,State,"Agriculture,Rural & Environment, Social welfar...","Missing, Fisherman, Relief, Financial Assistan..."
1,AICTE SHORT TERM TRAINING PROGRAMME-SFURTI SCHEME,astpss,"Short Term Training Programme-SFURTI Program, ...","Financial Assistance : Limit of funding ₹ 4,00...",The institution should be AICTE approved.,Registration of New Institute: Step 01: Visit ...,Feedback Form Copy of Proceedings Completion R...,Central,Education & Learning,"Trainings, Financial Assistance, AICTE"
2,Burial and Ex-gratia Payment Scheme in Case of...,baepsicodouldwact,"Launched in 2014, the "" Burial and Ex-gratia P...","Funeral Assistance: ₹3,000 payable in case of ...",The deceased construction worker should have b...,Step 1: The interested applicant should visit ...,Aadhaar Card of the applicant (nominee/Legal h...,State,Social welfare & Empowerment,"Building Worker, Construction Workers, Unregis..."
3,Consortia & Tender Marketing Scheme,ctms,Promotion of the product of Micro and Small En...,Enlistment of the Unit for participating in Go...,Micro & Small Enterprises registered with NSIC...,"Step 01: The application form, in the prescrib...",A passport size photograph of each of the Prop...,Central,Business & Entrepreneurship,"Goods And Services Marketing, Turnkey Projects..."
4,Garuda Scheme for Funeral Expense,gsfe,Andhra Pradesh Brahmin Welfare Corporation (AB...,"Financial Assistance of ₹10,000/- for funeral ...",The applicant should be a close relative of th...,Registration and apply Step 01: Applicants hav...,Passport-size Photograph of the Applicant Aadh...,State,Social welfare & Empowerment,"Social Welfare, Financial Assistance, Deceased..."
...,...,...,...,...,...,...,...,...,...,...
3395,“Ishan Uday” Special Scholarship Scheme For No...,iu-sss-ner,A scholarship scheme by the Ministry of Educat...,"1) UGC will award 10,000 (ten thousand) fresh...",The applicant must be a domicile of NER. The p...,New Registration : Step 1: Visit the Registrat...,Domicile certificate to be issued by the compe...,Central,Education & Learning,"Scholarship, Financial Assistance"
3396,“Medical Camps (Allopathy and Indian systems o...,mcacism-giapsca,The sub-scheme “Medical Camps (Allopathy and I...,Free Health Checkup and Free Medicines. Awaren...,The applicant should be 60 years or above in a...,Step 1: The interested applicant should visit ...,Aadhaar Card. Birth Certificate / Age Proof. R...,State,Health & Wellness,"Medicine, Health, Checkup, Senior Citizen, Doctor"
3397,“RAKSHAK PURASKARS’’ Award,rpa,The Directorate of Women and Child Development...,The recipients of the awarded are given a scro...,The applicant should have shown exceptional co...,Step 1: In the prescribed format of the applic...,Passport Size Photograph (Duly Attested by a G...,State,"Social welfare & Empowerment, Public Safety,La...","Award, Crime, Women, Girl, Violence, Harrassment"
3398,"“Training in Coir” Component of the ""Developme...",ticcotdocs,The scheme “Training in Coir” Component of the...,"Stipend of ₹1,500 per month per trainee during...",The applicant should be a native of Puducherry...,Step 1: The interested applicant should take p...,Residential Certificate (for verifying native ...,State,Skills & Employment,"Skill, Training, Coir, Rural, Poor, Employment"
3399,₹ 5 Lakh Insurance Cover To Farmers,farmer-insurance,"Launched on 15 August 2018, the scheme ""₹5 Lak...",Financial Security: Provides ₹5 lakh insurance...,The applicant should be a resident farmer of T...,Step 1: The farmers do not need to apply for t...,Since the ₹5 Lakh Insurance Cover for Farmers ...,State,"Agriculture,Rural & Environment, Banking,Finan...","LIC, Insurance Coverage, Financial, Security"

In [59]:
df.head(20)

,scheme_name,slug,details,benefits,eligibility,application,documents,level,schemeCategory,tags
0,"""Immediate Relief Assistance"" under ""Welfare a...",ira-wrflsncs,"The scheme ""Immediate Relief Assistance"" is a ...","₹ 1,00,000, in two installments of ₹ 50,000 ea...",The applicant should be the family (legal heir...,Step 1: The interested applicant should visit ...,Photograph of the Family (Legal Heir) of the M...,State,"Agriculture,Rural & Environment, Social welfar...","Missing, Fisherman, Relief, Financial Assistan..."
1,AICTE SHORT TERM TRAINING PROGRAMME-SFURTI SCHEME,astpss,"Short Term Training Programme-SFURTI Program, ...","Financial Assistance : Limit of funding ₹ 4,00...",The institution should be AICTE approved.,Registration of New Institute: Step 01: Visit ...,Feedback Form Copy of Proceedings Completion R...,Central,Education & Learning,"Trainings, Financial Assistance, AICTE"
2,Burial and Ex-gratia Payment Scheme in Case of...,baepsicodouldwact,"Launched in 2014, the "" Burial and Ex-gratia P...","Funeral Assistance: ₹3,000 payable in case of ...",The deceased construction worker should have b...,Step 1: The interested applicant should visit ...,Aadhaar Card of the applicant (nominee/Legal h...,State,Social welfare & Empowerment,"Building Worker, Construction Workers, Unregis..."
3,Consortia & Tender Marketing Scheme,ctms,Promotion of the product of Micro and Small En...,Enlistment of the Unit for participating in Go...,Micro & Small Enterprises registered with NSIC...,"Step 01: The application form, in the prescrib...",A passport size photograph of each of the Prop...,Central,Business & Entrepreneurship,"Goods And Services Marketing, Turnkey Projects..."
4,Garuda Scheme for Funeral Expense,gsfe,Andhra Pradesh Brahmin Welfare Corporation (AB...,"Financial Assistance of ₹10,000/- for funeral ...",The applicant should be a close relative of th...,Registration and apply Step 01: Applicants hav...,Passport-size Photograph of the Applicant Aadh...,State,Social welfare & Empowerment,"Social Welfare, Financial Assistance, Deceased..."
5,Incentive For The Intra Caste Marriage within ...,ifticmwstc,"The scheme ""Incentive for Intra Caste Marriage...","An incentive of ₹2,00,000/- is provided to the...",The couple should be residing in Karnataka. Bo...,Step 1: Visit the official website of the Trib...,Aadhaar Card Bank Account Details Marriage Pro...,State,Social welfare & Empowerment,"Intra Caste, Marriage, Schedule Tribe, Incenti..."
6,Incentive Scheme for MSMEs in Powerloom Sector...,ismpsscis,The scheme “State Capital Investment Subsidy” ...,20% of Fixed Capital Investment on Plant and m...,The Scheme shall be generally applicable to al...,"A micro, small or medium enterprise in Powerlo...",A copy of the Memorandum of Association and Ar...,State,Business & Entrepreneurship,"Powerloom, Incentives, State Capital Investmen..."
7,Indira Mahila Shakti Udyam Protsahan Yojana,imspesy,The Indira Mahila Shakti Udyam Protsahan Yojan...,"Loan Limit Loan amount of ₹ 50,00,000/- to ind...",The applicant's age should be 18 years or more...,Registration Step-1: Applicant have to visit t...,Aadhar card. Address proof. Bank account state...,State,Women and Child,"Women, Empowerment, Development, Motivaction"
8,Mukhyamantri Shramik Aujaar Sahayata Yojana,msasy,The Labor Department of Chhattisgarh launched ...,Tool kits can given free of cost to the regist...,The Applicant must be a native of Chhattisgarh...,Registration of a Construction Worker Under C...,Bank passbook photocopy. Self-declaration cert...,State,Social welfare & Empowerment,"Financial Assistance, Construction Workers, La..."
9,Nirman Shramik Jeevan va Bhavishya Suraksha Yo...,nsjbsy,"Launched in 2016, the scheme ""Nirman Shramik J...",Pradhan Mantri Suraksha Bima Yojana (PMSBY) 10...,1. The applicant must be registered as a bene...,REGISTRATION Step 1: Visit the Official Portal...,Copy of Beneficiary Registration Identity Card...,State,Health & Wellness,"Medical, Insurance, Health, Labor, Premium, Co..."
10,Pre-Matric Scholarship for Backward Class Stud...,pmsfbcs,"The scheme ""Pre-Matric Scholarship for Backwar...",Classes 6th to 8th Boys: ₹20/- per month Girls...,The applicant should be a student of classes 6...,Step 1: The interested applicant should visit ...,Caste Certificate Income Certificate Land Owne...,State,Education & Learning,"Financial Assistance, Backward Class, Student,..."
11,Safai Karmakaar Ke Putr/Putri Hetu Vishesh Coa...,skhvc,Labor Department of Chhattisgarh State started...,The fee for special coaching for admission in ...,Children of registered sanitation workers will...,Unregistered Applicant : All the applicant hav...,Aadhar card. Labor registration Card. Scholars...,State,Education & Learning,"Education, Coaching"
12,The West Bengal Incentive Scheme: Additional I...,wbisaito,“Additional Incentive for Adventure Tour Opera...,Group A: 60% Group B: 70% Group C: 80% Group ...,The Scheme shall be generally applicable to al...,Registration Process: Step 01: Visit the offic...,Documents required for the Registration and El...,State,Business & Entrepreneurship,"Tourism, Incentives, Tour Operators, Tourism U..."
13,The West Bengal Incentive Scheme: Additional I...,wbisaige,“Additional Incentive on Generation of Employm...,"Group A, B, C & D areas: 60% for a period of 5...",The Scheme shall be generally applicable to al...,Registration Process: Step 1: Visit the offici...,Documents required for the Registration and El...,State,Business & Entrepreneurship,"Tourism, Incentives, Waiver, Tourism Units, En..."
14,The West Bengal Incentive Scheme: Capacity Uti...,wbiscu,The scheme “State Capital Investment Subsidy” ...,"Pattern of Assistance: 50%, subject to a maxim...",The Scheme shall be generally applicable to al...,Registration Process: Step 1: Visit the offici...,Documents required for the Registration and El...,State,Business & Entrepreneurship,"Tourism, Entrepreneurship, Capacity Utilisatio..."
15,The West Bengal Incentive Scheme: Interest Sub...,wbisistl,“Interest Subsidy on Term Loan” is a sub schem...,"Group-'A’ and ‘B' areas: 50%, subject to a lim...",The Scheme shall be generally applicable to al...,Registration Process: Step 1: Visit the offici...,Documents required for the Registration and El...,State,Business & Entrepreneurship,"Tourism, Incentives, Interest Subsidy, Tourism..."
16,The West Bengal Incentive Scheme: Reimbursemen...,wbisrsdrf,“Reimbursement of Stamp Duty and Registration ...,"Group A and B: 50%, Group C and D: 60%, Specia...",The Scheme shall be generally applicable to al...,Registration Process: Step 1: Visit the offici...,Documents required for the Registration and El...,State,Business & Entrepreneurship,"Tourism, Incentives, Stamp Duty, Tourism Units..."
17,The West Bengal Incentive Scheme: State Capita...,wbisscis,The scheme “State Capital Investment Subsidy” ...,"Group A: 7.5%, subject to a limit of ₹ 1,00,00...",The Scheme shall be generally applicable to al...,Registration Process: Step 1: Visit the offici...,Documents required for the Registration and El...,State,Business & Entrepreneurship,"Tourism, Incentives, State Capital Investment ..."
18,The West Bengal Incentive Scheme: Subsidy for ...,wbissqi,“Subsidy for Quality Improvement” is a sub sch...,"50%, subject to a maximum of ₹ 7,50,000/-.",The Scheme shall be generally applicable to al...,Registration Process: Step 1: Visit the offici...,Documents required for the Registration and El...,State,Business & Entrepreneurship,"Tourism, Incentives, Quality Improvement, Tour..."
19,The West Bengal Incentive Scheme: Tourism Prom...,wbistpais,The scheme “State Capital Investment Subsidy” ...,Pattern of Assistance: Assistance at the rate ...,The Scheme shall be generally applicable to al...,Registration Process: Step 1: Visit the offici...,Documents required for the Registration and El...,State,Business & Entrepreneurship,"Tourism, Tourism Promotion, Interest Subsidy, ..."

In [60]:
df.isnull().sum()

scheme_name       0
slug              0
details           0
benefits          0
eligibility       0
application       0
documents         0
level             0
schemeCategory    0
tags              0
dtype: int64

In [61]:
df.drop(columns=["Unnamed: 9"], errors="ignore", inplace=True)
df.head()

,scheme_name,slug,details,benefits,eligibility,application,documents,level,schemeCategory,tags
0,"""Immediate Relief Assistance"" under ""Welfare a...",ira-wrflsncs,"The scheme ""Immediate Relief Assistance"" is a ...","₹ 1,00,000, in two installments of ₹ 50,000 ea...",The applicant should be the family (legal heir...,Step 1: The interested applicant should visit ...,Photograph of the Family (Legal Heir) of the M...,State,"Agriculture,Rural & Environment, Social welfar...","Missing, Fisherman, Relief, Financial Assistan..."
1,AICTE SHORT TERM TRAINING PROGRAMME-SFURTI SCHEME,astpss,"Short Term Training Programme-SFURTI Program, ...","Financial Assistance : Limit of funding ₹ 4,00...",The institution should be AICTE approved.,Registration of New Institute: Step 01: Visit ...,Feedback Form Copy of Proceedings Completion R...,Central,Education & Learning,"Trainings, Financial Assistance, AICTE"
2,Burial and Ex-gratia Payment Scheme in Case of...,baepsicodouldwact,"Launched in 2014, the "" Burial and Ex-gratia P...","Funeral Assistance: ₹3,000 payable in case of ...",The deceased construction worker should have b...,Step 1: The interested applicant should visit ...,Aadhaar Card of the applicant (nominee/Legal h...,State,Social welfare & Empowerment,"Building Worker, Construction Workers, Unregis..."
3,Consortia & Tender Marketing Scheme,ctms,Promotion of the product of Micro and Small En...,Enlistment of the Unit for participating in Go...,Micro & Small Enterprises registered with NSIC...,"Step 01: The application form, in the prescrib...",A passport size photograph of each of the Prop...,Central,Business & Entrepreneurship,"Goods And Services Marketing, Turnkey Projects..."
4,Garuda Scheme for Funeral Expense,gsfe,Andhra Pradesh Brahmin Welfare Corporation (AB...,"Financial Assistance of ₹10,000/- for funeral ...",The applicant should be a close relative of th...,Registration and apply Step 01: Applicants hav...,Passport-size Photograph of the Applicant Aadh...,State,Social welfare & Empowerment,"Social Welfare, Financial Assistance, Deceased..."

In [62]:
df1=df.head(10)
df1

,scheme_name,slug,details,benefits,eligibility,application,documents,level,schemeCategory,tags
0,"""Immediate Relief Assistance"" under ""Welfare a...",ira-wrflsncs,"The scheme ""Immediate Relief Assistance"" is a ...","₹ 1,00,000, in two installments of ₹ 50,000 ea...",The applicant should be the family (legal heir...,Step 1: The interested applicant should visit ...,Photograph of the Family (Legal Heir) of the M...,State,"Agriculture,Rural & Environment, Social welfar...","Missing, Fisherman, Relief, Financial Assistan..."
1,AICTE SHORT TERM TRAINING PROGRAMME-SFURTI SCHEME,astpss,"Short Term Training Programme-SFURTI Program, ...","Financial Assistance : Limit of funding ₹ 4,00...",The institution should be AICTE approved.,Registration of New Institute: Step 01: Visit ...,Feedback Form Copy of Proceedings Completion R...,Central,Education & Learning,"Trainings, Financial Assistance, AICTE"
2,Burial and Ex-gratia Payment Scheme in Case of...,baepsicodouldwact,"Launched in 2014, the "" Burial and Ex-gratia P...","Funeral Assistance: ₹3,000 payable in case of ...",The deceased construction worker should have b...,Step 1: The interested applicant should visit ...,Aadhaar Card of the applicant (nominee/Legal h...,State,Social welfare & Empowerment,"Building Worker, Construction Workers, Unregis..."
3,Consortia & Tender Marketing Scheme,ctms,Promotion of the product of Micro and Small En...,Enlistment of the Unit for participating in Go...,Micro & Small Enterprises registered with NSIC...,"Step 01: The application form, in the prescrib...",A passport size photograph of each of the Prop...,Central,Business & Entrepreneurship,"Goods And Services Marketing, Turnkey Projects..."
4,Garuda Scheme for Funeral Expense,gsfe,Andhra Pradesh Brahmin Welfare Corporation (AB...,"Financial Assistance of ₹10,000/- for funeral ...",The applicant should be a close relative of th...,Registration and apply Step 01: Applicants hav...,Passport-size Photograph of the Applicant Aadh...,State,Social welfare & Empowerment,"Social Welfare, Financial Assistance, Deceased..."
5,Incentive For The Intra Caste Marriage within ...,ifticmwstc,"The scheme ""Incentive for Intra Caste Marriage...","An incentive of ₹2,00,000/- is provided to the...",The couple should be residing in Karnataka. Bo...,Step 1: Visit the official website of the Trib...,Aadhaar Card Bank Account Details Marriage Pro...,State,Social welfare & Empowerment,"Intra Caste, Marriage, Schedule Tribe, Incenti..."
6,Incentive Scheme for MSMEs in Powerloom Sector...,ismpsscis,The scheme “State Capital Investment Subsidy” ...,20% of Fixed Capital Investment on Plant and m...,The Scheme shall be generally applicable to al...,"A micro, small or medium enterprise in Powerlo...",A copy of the Memorandum of Association and Ar...,State,Business & Entrepreneurship,"Powerloom, Incentives, State Capital Investmen..."
7,Indira Mahila Shakti Udyam Protsahan Yojana,imspesy,The Indira Mahila Shakti Udyam Protsahan Yojan...,"Loan Limit Loan amount of ₹ 50,00,000/- to ind...",The applicant's age should be 18 years or more...,Registration Step-1: Applicant have to visit t...,Aadhar card. Address proof. Bank account state...,State,Women and Child,"Women, Empowerment, Development, Motivaction"
8,Mukhyamantri Shramik Aujaar Sahayata Yojana,msasy,The Labor Department of Chhattisgarh launched ...,Tool kits can given free of cost to the regist...,The Applicant must be a native of Chhattisgarh...,Registration of a Construction Worker Under C...,Bank passbook photocopy. Self-declaration cert...,State,Social welfare & Empowerment,"Financial Assistance, Construction Workers, La..."
9,Nirman Shramik Jeevan va Bhavishya Suraksha Yo...,nsjbsy,"Launched in 2016, the scheme ""Nirman Shramik J...",Pradhan Mantri Suraksha Bima Yojana (PMSBY) 10...,1. The applicant must be registered as a bene...,REGISTRATION Step 1: Visit the Official Portal...,Copy of Beneficiary Registration Identity Card...,State,Health & Wellness,"Medical, Insurance, Health, Labor, Premium, Co..."

In [63]:
def step1(x):
    for i in x:
        a = str(i).lower()
        p = re.sub(r'[^a-z0-9]', ' ', a)
        print(p)

In [64]:
step1(df1["scheme_name"])

 immediate relief assistance  under  welfare and relief for fishermen during lean seasons and natural calamities scheme
aicte short term training programme sfurti scheme
burial and ex gratia payment scheme in case of death of unregistered laborer during work at construction site
consortia   tender marketing scheme
garuda scheme for funeral expense
incentive for the intra caste marriage within scheduled tribe community
incentive scheme for msmes in powerloom sector  state capital investment subsidy
indira mahila shakti udyam protsahan yojana
mukhyamantri shramik aujaar sahayata yojana
nirman shramik jeevan va bhavishya suraksha yojana

In [65]:
nltk.download('punkt_tab')
s= 'aicte short term training programme sfurti scheme'
words = word_tokenize(s)
print(words)

['aicte', 'short', 'term', 'training', 'programme', 'sfurti', 'scheme']

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

In [66]:
# Phase 1 + 2: Data structuring + eligibility matching engine
import os
import math
import re

# ---------- Phase 1: Prepare and structure dataset ----------
df_phase = df.copy()
df_phase.columns = [c.strip().lower().replace(" ", "_") for c in df_phase.columns]


def _pick_col(frame, candidates):
    for c in candidates:
        if c in frame.columns:
            return c
    return None


scheme_col = _pick_col(df_phase, ["scheme_name", "scheme", "name", "title"])
eligibility_col = _pick_col(df_phase, ["eligibility", "eligibility_criteria", "eligible_beneficiaries"])
benefits_col = _pick_col(df_phase, ["benefits", "benefit", "description", "details"])
documents_col = _pick_col(df_phase, ["documents", "required_documents", "document_required"])
application_col = _pick_col(df_phase, ["application", "how_to_apply", "application_link", "apply_link", "website"])

if scheme_col is None or eligibility_col is None:
    raise ValueError("Required columns not found. Need at least scheme_name and eligibility-type columns.")

states_master = [
    "andhra pradesh", "arunachal pradesh", "assam", "bihar", "chhattisgarh", "goa", "gujarat", "haryana",
    "himachal pradesh", "jharkhand", "karnataka", "kerala", "madhya pradesh", "maharashtra", "manipur",
    "meghalaya", "mizoram", "nagaland", "odisha", "punjab", "rajasthan", "sikkim", "tamil nadu", "telangana",
    "tripura", "uttar pradesh", "uttarakhand", "west bengal", "delhi", "jammu and kashmir", "ladakh",
    "andaman and nicobar", "chandigarh", "dadra and nagar haveli and daman and diu", "lakshadweep", "puducherry"
]

category_keywords = ["general", "sc", "st", "obc", "minority", "ews"]
occupation_keywords = ["student", "farmer", "labour", "worker", "woman", "women", "entrepreneur", "senior citizen", "pregnant", "widow", "disabled"]


def parse_age_range(text):
    t = str(text).lower()

    between = re.search(r"(\d{1,2})\s*(?:to|-|–)\s*(\d{1,2})\s*(?:years?|yrs?)", t)
    if between:
        a, b = int(between.group(1)), int(between.group(2))
        return float(min(a, b)), float(max(a, b)), "between"

    min_match = re.search(r"(?:above|greater than|minimum|min|age\s*>=?)\s*(\d{1,2})", t)
    max_match = re.search(r"(?:below|less than|maximum|max|age\s*<=?|upto|up to)\s*(\d{1,2})", t)

    if min_match and max_match:
        min_age = float(min_match.group(1))
        max_age = float(max_match.group(1))
        if min_age > max_age:
            min_age, max_age = max_age, min_age
        return min_age, max_age, "between"

    if min_match:
        return float(min_match.group(1)), 120.0, "min_only"

    if max_match:
        return 0.0, float(max_match.group(1)), "max_only"

    return 0.0, 120.0, "none"


def parse_income_limit(text):
    t = str(text).lower().replace(",", "")

    if not any(k in t for k in ["income", "annual", "year", "monthly", "rs", "rupee", "rupaye", "₹"]):
        return float("inf")

    nums = [float(x) for x in re.findall(r"\b\d{4,8}\b", t)]
    if not nums:
        return float("inf")

    return max(nums)


def parse_state_list(text):
    t = str(text).lower()
    if "all india" in t or "all states" in t or "pan india" in t or "nationwide" in t:
        return ["all"]
    found = [s for s in states_master if s in t]
    return sorted(set(found))


def parse_keyword_list(text, keywords):
    t = str(text).lower()
    found = [k for k in keywords if k in t]
    return sorted(set(found))


df_phase["eligibility_raw"] = df_phase[eligibility_col].fillna("").astype(str)
df_phase[["min_age", "max_age", "age_rule_type"]] = df_phase["eligibility_raw"].apply(lambda x: pd.Series(parse_age_range(x)))
df_phase["max_income"] = df_phase["eligibility_raw"].apply(parse_income_limit)
df_phase["eligible_states"] = df_phase["eligibility_raw"].apply(parse_state_list)
df_phase["eligible_categories"] = df_phase["eligibility_raw"].apply(lambda x: parse_keyword_list(x, category_keywords))
df_phase["occupation_tags"] = df_phase["eligibility_raw"].apply(lambda x: parse_keyword_list(x, occupation_keywords))

# Optional export for teammates
out_path = "C:/Users/ASUS/OneDrive/Documents/GITHUB/SchemeSathi/Dataset/schemes_processed.csv"
df_phase.to_csv(out_path, index=False)
print(f"Processed dataset saved: {out_path}")


# ---------- Phase 2: Matching + ranking engine ----------
def get_eligible_schemes(user_profile, data=df_phase, top_k=10, threshold=55):
    """
    user_profile keys:
    age (int), state (str), income (float), category (str), occupation (str), special_status (list/str)
    """

    age = int(user_profile.get("age", 0) or 0)
    state = str(user_profile.get("state", "")).strip().lower()
    income = float(user_profile.get("income", 0) or 0)
    category = str(user_profile.get("category", "")).strip().lower()
    occupation = str(user_profile.get("occupation", "")).strip().lower()

    results = []

    for _, row in data.iterrows():
        score = 0
        matched_rules = []
        failed_rules = []

        # Age scoring with human-friendly explanation labels.
        min_age = float(row.get("min_age", 0) if pd.notna(row.get("min_age", 0)) else 0)
        max_age = float(row.get("max_age", 120) if pd.notna(row.get("max_age", 120)) else 120)
        age_rule_type = str(row.get("age_rule_type", "none"))

        age_ok = min_age <= age <= max_age
        if age_rule_type == "none":
            score += 8
            matched_rules.append("No specific age criteria mentioned")
        elif age_rule_type == "min_only":
            if age_ok:
                score += 20
                matched_rules.append(f"Age {int(min_age)}+")
            else:
                failed_rules.append(f"Age must be at least {int(min_age)}")
        elif age_rule_type == "max_only":
            if age_ok:
                score += 20
                matched_rules.append(f"Age up to {int(max_age)}")
            else:
                failed_rules.append(f"Age must be up to {int(max_age)}")
        else:
            if age_ok:
                score += 20
                matched_rules.append(f"Age between {int(min_age)} and {int(max_age)}")
            else:
                failed_rules.append(f"Age not in range {int(min_age)}-{int(max_age)}")

        # Income (25)
        max_income = row.get("max_income", float("inf"))
        if pd.isna(max_income):
            max_income = float("inf")
        if income <= float(max_income):
            score += 25
            if math.isinf(float(max_income)):
                matched_rules.append("No explicit income ceiling")
            else:
                matched_rules.append(f"Income <= {int(max_income)}")
        else:
            failed_rules.append(f"Income above limit ({int(max_income)})")

        # State (25)
        row_states = row.get("eligible_states", [])
        if isinstance(row_states, str):
            row_states_l = row_states.lower()
            state_ok = ("all" in row_states_l) or (state and state in row_states_l)
        else:
            row_states_set = {str(x).lower() for x in row_states}
            state_ok = ("all" in row_states_set) or (state in row_states_set)

        if state_ok or not state:
            score += 25
            matched_rules.append("State matched")
        else:
            failed_rules.append("State not matched")

        # Category (20)
        row_categories = row.get("eligible_categories", [])
        if isinstance(row_categories, str):
            cat_ok = (category in row_categories.lower()) if category else True
        else:
            cat_ok = (not row_categories) or (category in {str(x).lower() for x in row_categories}) if category else True

        if cat_ok:
            score += 20
            matched_rules.append("Category matched or open")
        else:
            failed_rules.append("Category not matched")

        # Occupation/status (10)
        row_occ = row.get("occupation_tags", [])
        if isinstance(row_occ, str):
            occ_ok = (occupation in row_occ.lower()) if occupation else True
        else:
            occ_ok = (not row_occ) or (occupation in {str(x).lower() for x in row_occ}) if occupation else True

        if occ_ok:
            score += 10
            matched_rules.append("Occupation/status matched or open")
        else:
            failed_rules.append("Occupation/status not matched")

        if score >= threshold:
            results.append({
                "scheme_name": row.get(scheme_col, "Unknown Scheme"),
                "match_score": int(score),
                "why_eligible": "; ".join(matched_rules[:3]),
                "matched_rules": matched_rules,
                "failed_rules": failed_rules,
                "benefits": row.get(benefits_col, "") if benefits_col else "",
                "documents": row.get(documents_col, "") if documents_col else "",
                "application_link": row.get(application_col, "") if application_col else "",
                "eligibility_text": row.get("eligibility_raw", "")
            })

    results = sorted(results, key=lambda x: x["match_score"], reverse=True)
    return results[:top_k]


# Quick validation sample
sample_user = {
    "age": 28,
    "state": "Maharashtra",
    "income": 45000,
    "category": "SC",
    "occupation": "student"
}

sample_results = get_eligible_schemes(sample_user, top_k=5)
print(f"Top matches found: {len(sample_results)}")
pd.DataFrame(sample_results)[["scheme_name", "match_score", "why_eligible"]].head(5)

Processed dataset saved: C:/Users/ASUS/OneDrive/Documents/GITHUB/SchemeSathi/Dataset/schemes_processed.csv
Top matches found: 5

,scheme_name,match_score,why_eligible
0,Karma Veer Dadasaheb Gaikwad Sabalikaran & Swa...,100,Age between 18 and 60; No explicit income ceil...
1,Mahila Kisan Yojana (Maharashtra),100,Age between 18 and 50; Income <= 120000; State...
2,Micro Credit Finance,100,Age between 18 and 50; Income <= 120000; State...
3,Agriculture Academic Studies Scheme,88,No specific age criteria mentioned; No explici...
4,Assam Arogya Nidhi Scheme,88,No specific age criteria mentioned; No explici...

In [67]:
test_profiles = [
    {"name": "Student_SC_MH", "age": 20, "state": "Maharashtra", "income": 30000, "category": "SC", "occupation": "student"},
    {"name": "Farmer_OBC_UP", "age": 42, "state": "Uttar Pradesh", "income": 60000, "category": "OBC", "occupation": "farmer"},
    {"name": "Senior_General_KA", "age": 67, "state": "Karnataka", "income": 25000, "category": "General", "occupation": "senior citizen"},
    {"name": "Woman_Entrepreneur_TN", "age": 31, "state": "Tamil Nadu", "income": 90000, "category": "General", "occupation": "entrepreneur"},
    {"name": "Worker_ST_OD", "age": 36, "state": "Odisha", "income": 40000, "category": "ST", "occupation": "worker"},
]

for p in test_profiles:
    results = get_eligible_schemes(p, top_k=5)
    print(f"\n=== {p['name']} | Matches: {len(results)} ===")
    if results:
        display(pd.DataFrame(results)[["scheme_name", "match_score", "why_eligible"]].head(5))
    else:
        print("No matches found.")

=== Student_SC_MH | Matches: 5 ===

,scheme_name,match_score,why_eligible
0,Financial Assistance To Cultural Organizations...,100,Age up to 25; No explicit income ceiling; Stat...
1,Karma Veer Dadasaheb Gaikwad Sabalikaran & Swa...,100,Age between 18 and 60; No explicit income ceil...
2,Mahila Kisan Yojana (Maharashtra),100,Age between 18 and 50; Income <= 120000; State...
3,Micro Credit Finance,100,Age between 18 and 50; Income <= 120000; State...
4,Shaktidoot Scheme,100,Age up to 20; No explicit income ceiling; Stat...

=== Farmer_OBC_UP | Matches: 5 ===

,scheme_name,match_score,why_eligible
0,Centrally Sponsored Scheme of Post-Matric Scho...,88,No specific age criteria mentioned; No explici...
1,Computer Training Scheme,88,No specific age criteria mentioned; Income <= ...
2,ICAR Junior Research Fellowship For Post-Gradu...,88,No specific age criteria mentioned; No explici...
3,ICAR Senior Research Fellowship For Post-Gradu...,88,No specific age criteria mentioned; No explici...
4,Agriculture Academic Studies Scheme,78,No specific age criteria mentioned; No explici...

=== Senior_General_KA | Matches: 5 ===

,scheme_name,match_score,why_eligible
0,ICAR Junior Research Fellowship For Post-Gradu...,88,No specific age criteria mentioned; No explici...
1,Airavata Scheme,80,Age 21+; Income <= 500000; State matched
2,Prerana (micro Credit Finance) Scheme,80,Age 21+; Income <= 200000; State matched
3,Shaktidoot Scheme,80,No explicit income ceiling; State matched; Cat...
4,Agriculture Academic Studies Scheme,78,No specific age criteria mentioned; No explici...

=== Woman_Entrepreneur_TN | Matches: 5 ===

,scheme_name,match_score,why_eligible
0,New Entrepreneur-cum-enterprise Development Sc...,100,Age between 21 and 35; No explicit income ceil...
1,Afforestation Schemes Providing Incentives And...,88,No specific age criteria mentioned; No explici...
2,Chief Minister’s Comprehensive Health Insuranc...,88,No specific age criteria mentioned; Income <= ...
3,District Central Cooperative Banks and through...,88,No specific age criteria mentioned; No explici...
4,District Central Cooperative Banks and through...,88,No specific age criteria mentioned; No explici...

=== Worker_ST_OD | Matches: 5 ===

,scheme_name,match_score,why_eligible
0,"""Input Assistance to Farmers for Taking up Fis...",100,Age 5+; No explicit income ceiling; State matched
1,Marriage Assistance (O.B.O.C.W.W.B),100,Age 18+; No explicit income ceiling; State mat...
2,SUBHADRA,100,Age up to 60; Income <= 250000; State matched
3,Assam Arogya Nidhi Scheme,88,No specific age criteria mentioned; No explici...
4,Assistance for Funeral Expenses (O.B.O.C.W.W.B),88,No specific age criteria mentioned; No explici...

In [69]:
sample = get_eligible_schemes(
    {"age": 28, "state": "Maharashtra", "income": 45000, "category": "SC", "occupation": "student"},
    top_k=1
)

required_keys = {
    "scheme_name", "match_score", "why_eligible", "matched_rules", "failed_rules",
    "benefits", "documents", "application_link", "eligibility_text"
}

if not sample:
    print("No sample result found. Lower threshold and test again.")
else:
    missing = required_keys - set(sample[0].keys())
    print("Missing keys:", missing if missing else "None")
    print("Schema OK" if not missing else "Schema not complete")
    display(pd.DataFrame(sample))

Missing keys: None
Schema OK

,scheme_name,match_score,why_eligible,matched_rules,failed_rules,benefits,documents,application_link,eligibility_text
0,Karma Veer Dadasaheb Gaikwad Sabalikaran & Swa...,100,Age between 18 and 60; No explicit income ceil...,"[Age between 18 and 60, No explicit income cei...",[],The beneficiary is provided with 2-acre irriga...,BPL Card Aadhaar Card. Proof of Age (Birth Cer...,Step 1: Visit the District Social Welfare Offi...,The applicant should be a citizen of India. Th...

### SchemeSathi Matching API Contract

Input profile (dict):
- age: int
- state: str
- income: float
- category: str
- occupation: str

Function:
- get_eligible_schemes(user_profile, top_k=10, threshold=55)

Output (list of dict):
- scheme_name
- match_score
- why_eligible
- matched_rules
- failed_rules
- benefits
- documents
- application_link
- eligibility_text